export const headFiles = [
    "head-aardvark.svg", "head-cow.svg", "head-lips.svg", "head-robot.svg",
    "head-abstract.svg", "head-crab.svg", "head-lipstick2.svg", "head-rock.svg",
    "head-ape.svg", "head-crane.svg", "head-lock.svg", "head-rosebud.svg",
    "head-bag.svg", "head-croc-hat.svg", "head-macaroni.svg", "head-ruler-triangular.svg",
    "head-bagpipe.svg", "head-crown.svg", "head-mailbox.svg", "head-saguaro.svg",
    "head-banana.svg", "head-crt-bsod.svg", "head-maze.svg", "head-sailboat.svg",
    "head-bank.svg", "head-crystalball.svg", "head-microwave.svg", "head-sandwich.svg",
    "head-baseball-gameball.svg", "head-diamond-blue.svg", "head-milk.svg", "head-saturn.svg",
    "head-basketball.svg", "head-diamond-red.svg", "head-mirror.svg", "head-saw.svg",
    "head-bat.svg", "head-dictionary.svg", "head-mixer.svg", "head-scorpion.svg",
    "head-bear.svg", "head-dino.svg", "head-moon.svg", "head-shark.svg",
    "head-beer.svg", "head-dna.svg", "head-moose.svg", "head-shower.svg",
    "head-beet.svg", "head-dog.svg", "head-mosquito.svg", "head-skateboard.svg",
    "head-bell.svg", "head-doughnut.svg", "head-mountain-snowcap.svg", "head-skeleton-hat.svg",
    "head-bigfoot-yeti.svg", "head-drill.svg", "head-mouse.svg", "head-skilift.svg",
    "head-bigfoot.svg", "head-duck.svg", "head-mug.svg", "head-smile.svg",
    "head-blackhole.svg", "head-ducky.svg", "head-mushroom.svg", "head-snowglobe.svg",
    "head-blueberry.svg", "head-earth.svg", "head-mustard.svg", "head-snowmobile.svg",
    "head-bomb.svg", "head-egg.svg", "head-nigiri.svg", "head-spaghetti.svg",
    "head-bonsai.svg", "head-faberge.svg", "head-noodles.svg", "head-sponge.svg",
    "head-boombox.svg", "head-factory-dark.svg", "head-onion.svg", "head-squid.svg",
    "head-boot.svg", "head-fan.svg", "head-orangutan.svg", "head-stapler.svg",
    "head-box.svg", "head-fence.svg", "head-orca.svg", "head-star-sparkles.svg",
    "head-boxingglove.svg", "head-film-35mm.svg", "head-otter.svg", "head-steak.svg",
    "head-brain.svg", "head-film-strip.svg", "head-outlet.svg", "head-sunset.svg",
    "head-bubble-speech.svg", "head-fir.svg", "head-owl.svg", "head-taco-classic.svg",
    "head-bubblegum.svg", "head-firehydrant.svg", "head-oyster.svg", "head-taxi.svg",
    "head-burger-dollarmenu.svg", "head-flamingo.svg", "head-paintbrush.svg", "head-thumbsup.svg",
    "head-cake.svg", "head-flower.svg", "head-panda.svg", "head-toaster.svg",
    "head-calculator.svg", "head-fox.svg", "head-paperclip.svg", "head-toiletpaper-full.svg",
    "head-calendar.svg", "head-frog.svg", "head-peanut.svg", "head-tooth.svg",
    "head-camcorder.svg", "head-garlic.svg", "head-pencil-tip.svg", "head-toothbrush-fresh.svg",
    "head-cannedham.svg", "head-gavel.svg", "head-peyote.svg", "head-tornado.svg",
    "head-car.svg", "head-ghost-B.svg", "head-piano.svg", "head-trashcan.svg",
    "head-cash-register.svg", "head-glasses-big.svg", "head-pickle.svg", "head-turing.svg",
    "head-cassettetape.svg", "head-gnome.svg", "head-pie.svg", "head-ufo.svg",
    "head-cat.svg", "head-goat.svg", "head-piggybank.svg", "head-undead.svg",
    "head-cd.svg", "head-goldcoin.svg", "head-pill.svg", "head-unicorn.svg",
    "head-chain.svg", "head-goldfish.svg", "head-pillow.svg", "head-vent.svg",
    "head-chainsaw.svg", "head-grouper.svg", "head-pineapple.svg", "head-void.svg",
    "head-chameleon.svg", "head-hair.svg", "head-pipe.svg", "head-volcano.svg",
    "head-chart-bars.svg", "head-hardhat.svg", "head-pirateship.svg", "head-volleyball.svg",
    "head-cheese.svg", "head-heart.svg", "head-pizza.svg", "head-wall.svg",
    "head-chefhat.svg", "head-helicopter.svg", "head-plane.svg", "head-wallet.svg",
    "head-cherry.svg", "head-highheel.svg", "head-pop.svg", "head-wallsafe.svg",
    "head-chicken.svg", "head-hockeypuck.svg", "head-porkbao.svg", "head-washingmachine.svg",
    "head-chilli.svg", "head-horse-deepfried.svg", "head-potato.svg", "head-watch.svg",
    "head-chipboard.svg", "head-hotdog.svg", "head-pufferfish.svg", "head-watermelon.svg",
    "head-chips.svg", "head-house.svg", "head-pumpkin.svg", "head-wave.svg",
    "head-chocolate.svg", "head-icepop-b.svg", "head-pyramid.svg", "head-weed.svg",
    "head-cloud.svg", "head-igloo.svg", "head-queencrown.svg", "head-weight.svg",
    "head-clover.svg", "head-island.svg", "head-rabbit.svg", "head-werewolf.svg",
    "head-clutch.svg", "head-jellyfish.svg", "head-rainbow.svg", "head-whale-alive.svg",
    "head-coffeebean.svg", "head-jupiter.svg", "head-rangefinder.svg", "head-whale.svg",
    "head-cone.svg", "head-kangaroo.svg", "head-raven.svg", "head-wine.svg",
    "head-console-handheld.svg", "head-ketchup.svg", "head-retainer.svg", "head-wizardhat.svg",
    "head-cookie.svg", "head-laptop.svg", "head-rgb.svg", "head-zebra.svg",
    "head-cordlessphone.svg", "head-lightning-bolt.svg", "head-ring.svg", "head-washingmachine.svg"
  ];
 
  export const glassesFiles = [
    "glasses-hip-rose.svg", "glasses-square-fullblack.svg", "glasses-square-pink-purple-multi.svg",
    "glasses-square-black-eyes-red.svg", "glasses-square-green-blue-multi.svg", "glasses-square-red.svg",
    "glasses-square-black-rgb.svg", "glasses-square-grey-light.svg", "glasses-square-smoke.svg",
    "glasses-square-black.svg", "glasses-square-guava.svg", "glasses-square-teal.svg",
    "glasses-square-blue-med-saturated.svg", "glasses-square-honey.svg", "glasses-square-watermelon.svg",
    "glasses-square-blue.svg", "glasses-square-magenta.svg", "glasses-square-yellow-orange-multi.svg",
    "glasses-square-frog-green.svg", "glasses-square-orange.svg", "glasses-square-yellow-saturated.svg"
  ];

  export const bodyFiles = [
    "body-bege-bsod.svg", "body-darkbrown.svg", "body-grayscale-8.svg", "body-orange-yellow.svg", "body-redpinkish.svg",
    "body-bege-crt.svg", "body-darkpink.svg", "body-grayscale-9.svg", "body-orange.svg", "body-rust.svg",
    "body-blue-sky.svg", "body-foggrey.svg", "body-green.svg", "body-peachy-B.svg", "body-slimegreen.svg",
    "body-bluegrey.svg", "body-gold.svg", "body-gunk.svg", "body-peachy-a.svg", "body-teal-light.svg",
    "body-cold.svg", "body-grayscale-1.svg", "body-hotbrown.svg", "body-purple.svg", "body-teal.svg",
    "body-computerblue.svg", "body-grayscale-7.svg", "body-magenta.svg", "body-red.svg", "body-yellow.svg"
  ];

  export const accessoryFiles = [
    "accessory-1n.svg", "accessory-moon-block.svg", "accessory-aardvark.svg", "accessory-none.svg",
    "accessory-axe.svg", "accessory-oldshirt.svg", "accessory-belly-chameleon.svg", "accessory-pizza-bling.svg",
    "accessory-bird-flying.svg", "accessory-pocket-pencil.svg", "accessory-bird-side.svg", "accessory-rain.svg",
    "accessory-bling-anchor.svg", "accessory-rainbow-steps.svg", "accessory-bling-anvil.svg", "accessory-rgb.svg",
    "accessory-bling-arrow.svg", "accessory-robot.svg", "accessory-bling-cheese.svg", "accessory-safety-vest.svg",
    "accessory-bling-gold-ingot.svg", "accessory-scarf-clown.svg", "accessory-bling-love.svg", "accessory-secret-x.svg",
    "accessory-bling-mask.svg", "accessory-shirt-black.svg", "accessory-bling-rings.svg", "accessory-shrimp.svg",
    "accessory-bling-scissors.svg", "accessory-slimesplat.svg", "accessory-bling-sparkles.svg", "accessory-small-bling.svg",
    "accessory-body-gradient-checkerdisco.svg", "accessory-snowflake.svg", "accessory-body-gradient-dawn.svg", "accessory-stains-blood.svg",
    "accessory-body-gradient-dusk.svg", "accessory-stains-zombie.svg", "accessory-body-gradient-glacier.svg", "accessory-stripes-and-checks.svg",
    "accessory-body-gradient-ice.svg", "accessory-stripes-big-red.svg", "accessory-body-gradient-pride.svg", "accessory-stripes-blit.svg",
    "accessory-body-gradient-redpink.svg", "accessory-stripes-blue-med.svg", "accessory-body-gradient-sunset.svg", "accessory-stripes-brown.svg",
    "accessory-carrot.svg", "accessory-stripes-olive.svg", "accessory-chain-logo.svg", "accessory-stripes-red-cold.svg",
    "accessory-checker-RGB.svg", "accessory-sunset.svg", "accessory-checker-bigwalk-blue-prime.svg", "accessory-taxi-checkers.svg",
    "accessory-checker-bigwalk-greylight.svg", "accessory-tee-yo.svg", "accessory-checker-bigwalk-rainbow.svg", "accessory-text-yolo.svg",
    "accessory-checker-spaced-black.svg", "accessory-think.svg", "accessory-checker-spaced-white.svg", "accessory-tie-black-on-white.svg",
    "accessory-checker-vibrant.svg", "accessory-tie-dye.svg", "accessory-checkers-big-green.svg", "accessory-tie-purple-on-white.svg",
    "accessory-checkers-big-red-cold.svg", "accessory-tie-red.svg", "accessory-checkers-black.svg", "accessory-txt-a2+b2.svg",
    "accessory-checkers-blue.svg", "accessory-txt-cc.svg", "accessory-checkers-magenta-80.svg", "accessory-txt-cc2.svg",
    "accessory-chicken.svg", "accessory-txt-copy.svg", "accessory-cloud.svg", "accessory-txt-dao-black.svg",
    "accessory-clover.svg", "accessory-txt-doom.svg", "accessory-collar-sunset.svg", "accessory-txt-dope-text.svg",
    "accessory-cow.svg", "accessory-txt-foo-black.svg", "accessory-decay-gray-dark.svg", "accessory-txt-ico.svg",
    "accessory-decay-pride.svg", "accessory-txt-io.svg", "accessory-dinosaur.svg", "accessory-txt-lmao.svg",
    "accessory-dollar-bling.svg", "accessory-txt-lol.svg", "accessory-dragon.svg", "accessory-txt-mint.svg",
    "accessory-ducky.svg", "accessory-txt-nil-grey-dark.svg", "accessory-eth.svg", "accessory-txt-noun-f0f.svg",
    "accessory-eye.svg", "accessory-txt-noun-green.svg", "accessory-flash.svg", "accessory-txt-noun-multicolor.svg",
    "accessory-fries.svg", "accessory-txt-noun.svg", "accessory-glasses-logo-sun.svg", "accessory-txt-pi.svg",
    "accessory-glasses-logo.svg", "accessory-txt-pop.svg", "accessory-glasses.svg", "accessory-txt-rofl.svg",
    "accessory-grid-simple-bege.svg", "accessory-txt-we.svg", "accessory-heart.svg", "accessory-txt-yay.svg",
    "accessory-hoodiestrings-uneven.svg", "accessory-wall.svg", "accessory-id.svg", "accessory-wave.svg",
    "accessory-infinity.svg", "accessory-wet-money.svg", "accessory-insignia.svg", "accessory-woolweave-bicolor.svg",
    "accessory-leaf.svg", "accessory-woolweave-dirt.svg", "accessory-lightbulb.svg", "accessory-yingyang.svg",
    "accessory-lines-45-greens.svg", "body-bege.svg", "accessory-lines-45-rose.svg", "body-gray-scale-1.svg",
    "accessory-lp.svg", "body-gray-scale-9.svg", "accessory-marsface.svg", "body-ice-cold.svg",
    "accessory-matrix-white.svg"
  ];